### ISSUE TITLE
Tree inside TreeSummarizedExperiment is not subset

### ISSUE THREAD

**Issue by FelixErnst** [fionarhuang/TreeSummarizedExperiment#34]
Hi @fionarhuang,

starting with the recent changes, this example works now:

```
data("tinyTree")
# the count table
count <- matrix(rpois(100, 50), nrow = 10)
rownames(count) <- c(tinyTree$tip.label)
colnames(count) <- paste("C_", 1:10, sep = "_")
# The sample information
sampC <- data.frame(condition = rep(c("control", "trt"), each = 5),
                                     gender = sample(x = 1:2, size = 10, replace = TRUE))
rownames(sampC) <- colnames(count)
# build a TreeSummarizedExperiment object
tse <- TreeSummarizedExperiment(assays = list(count),
                                    colData = sampC,
                                    rowTree = tinyTree)

# does not work
tse["t2",]
>class: TreeSummarizedExperiment 
>dim: 1 10 
>metadata(0):
>assays(1): ''
>rownames(1): t2
>rowData names(0):
>colnames(10): C__1 C__2 ... C__9 C__10
>colData names(2): condition gender
>reducedDimNames(0):
>altExpNames(0):
>rowLinks: a LinkDataFrame (1 rows)
>rowTree: a phylo (10 leaves)
>colLinks: NULL
>colTree: NULL
```

However, the tree is not trimmed. Is that to be expected?

If not, mybe a call to `ape::keep.tip` needs to be added to https://github.com/fionarhuang/TreeSummarizedExperiment/blob/172dd3f698d0ccf74808b737e45d65acb0625ffe/R/allGenerics.R#L68

Thanks for any comment and explanation.

Felix

**Comment by fionarhuang** [comment]
Hi Felix,

In some case, tree might not exist anymore after trimming. That's why the tree is  kept to track nodes. If you are interested to trim the tree,  it could be done by trimming the tree using the `ape::drop.tip` or `ape::keep.tip` and update the tree slot using the function `changeTree`.

**Comment by FelixErnst** [comment]
Hi @fionarhuang,

Thanks for the explanation. I don't know, if it might be more helpful to trim the tree automatically, since you check the tree for dimension in the constructur function and drop dimensions from the `SummarizedExperiment`, if the tree is smaller. 

```
>z <- ape::keep.tip(tinyTree,1)
>tse <- TreeSummarizedExperiment(assays = list(count),
                                    colData = sampC,
                                    rowTree = z)
Warnmeldung:
In .linkFun(tree = rowTree, sce = sce, nodeLab = rowNodeLab, onRow = TRUE) :
  9 row(s) couldn't be matched to the tree and are/is removed. 
> tse
class: TreeSummarizedExperiment 
dim: 1 10 
metadata(0):
assays(1): ''
rownames(1): t2
rowData names(0):
colnames(10): C__1 C__2 ... C__9 C__10
colData names(2): condition gender
reducedDimNames(0):
altExpNames(0):
rowLinks: a LinkDataFrame (1 rows)
rowTree: a phylo (1 leaves)
colLinks: NULL
colTree: NULL
```

Me as user expects this to follow through the methods.



Would you have a look at a PR?

**Comment by fionarhuang** [comment]
Hi @FelixErnst,

In the example you posted, it's definitely better to trim the tree automatically. I am wondering whether it would be better to add a new function like `pruneByTree` to support it?

The concern to trim tree in the `subsetByNode` is when users subset a branch by internal nodes using the node number instead of node labels (trees might not provide labels on internal nodes). If we trim the tree, the node number is changed after trimming. This might lead to confusion and also lose tracking of nodes...

For example, if we subset by node `16` and trim the tree, the node number is changed to `6` instead of `16` in the rowLink data.  This might be an issue for users that need to keep tracking of the nodes. 
`
library(ggtree)
data("tinyTree")
newTree <- ape::keep.tip(phy = tinyTree, tip = 4:8)

fig1 <- ggtree(tinyTree, branch.length = "none") +
    geom_nodelab() +
    geom_text2(aes(label = node), color  = "red",
               vjust = 2)+
    xlim(-1, 7)

fig2 <- ggtree(newTree, branch.length = "none") +
    geom_nodelab() +
    geom_text2(aes(label = node), color  = "red",
               vjust = 2) +
    xlim(-1, 4)
cowplot::plot_grid(fig1, fig2)
`
![Screenshot 2020-07-13 at 18 29 06](https://user-images.githubusercontent.com/22393299/87329427-31f16c00-c537-11ea-9f79-185e2c795038.png)

**Comment by FelixErnst** [comment]
I get your point and I am not really an expert on tree semantic.

However, the point you are making is about metadata: which rows corresponds to which leaves. By using `ape::keep.tip` you keep the order of the results leaves, the same as you do, when you subset by `x[i,]`. So both will match and the connection is made through the `TreeSummarizedExperiment` object.

`subsetByNode` doesn't solve this problem and I would assume another function wouldn't help much. This would require the user to be aware of this behavior and have realized the necessity for it. I certainly didn't, because I want the tree to change with the rows. Maybe that is just me.

**Comment by FelixErnst** [comment]
So a few more questions:

1. I also see that you have similar methods already implemented, like `changeTree`, which is basically a setter for `rowTree` / `colTree`. Why wasn't that naming convention used?
2. the recent changes break some examples: `changeTree` doesn't work anymore. I guess this was due to change in setting the rownames to allow for rowname subsetting.
3. So the tree does not need to as long as the `data`, but cannot be bigger? Or does have to be the same dimension?
